# Generated by Django 5.1 on 2026-03-09 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('emoji', models.CharField(blank=True, help_text='Emoji para el menú', max_length=10, verbose_name='Emoji')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Categoría del menú',
                'verbose_name_plural': 'Categorías del menú',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('auto_response', models.TextField(blank=True, help_text='Texto que se envía automáticamente al seleccionar esta opción. Si está vacío, la IA responde.', verbose_name='Respuesta automática')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.menucategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría del menú',
                'verbose_name_plural': 'Subcategorías del menú',
                'ordering': ['order', 'name'],
            },
        ),
    ]
