# Generated by Django 5.1 on 2026-03-24 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('auto_response', models.TextField(blank=True, help_text='Texto que se envía automáticamente al seleccionar esta opción.', verbose_name='Respuesta automática')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menusubcategory', verbose_name='Subcategoría padre')),
            ],
            options={
                'verbose_name': 'Sub-subcategoría del menú',
                'verbose_name_plural': 'Sub-subcategorías del menú',
                'ordering': ['order', 'name'],
            },
        ),
    ]
