# Generated by Django 5.1 on 2026-03-09 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('industry', models.CharField(help_text='Ej: Taller mecánico, Odontología, Comercio', max_length=100, verbose_name='Rubro')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Teléfono, email, dirección, horarios, etc.', verbose_name='Información de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(default='gemini-2.0-flash', help_text='Modelo de Gemini a usar', max_length=100, verbose_name='Modelo de IA')),
                ('system_prompt', models.TextField(blank=True, help_text='Instrucciones para la IA sobre cómo comportarse y responder', verbose_name='Prompt del sistema')),
                ('knowledge_base', models.TextField(blank=True, help_text='Información del negocio: servicios, precios, horarios, preguntas frecuentes, etc. La IA usará esto para responder.', verbose_name='Base de conocimiento')),
                ('temperature', models.FloatField(default=0.7, help_text='Creatividad de la IA (0.0 = preciso, 1.0 = creativo)', verbose_name='Temperatura')),
                ('max_tokens', models.IntegerField(default=500, help_text='Largo máximo de respuesta', verbose_name='Tokens máximos')),
                ('classification_categories', models.JSONField(blank=True, default=list, help_text='Lista de clasificaciones para los leads. La IA asigna automáticamente, el recepcionista puede cambiarla.', verbose_name='Categorías de clasificación')),
                ('greeting_message', models.TextField(blank=True, help_text='Mensaje de bienvenida personalizado. Si está vacío, se genera uno automático.', verbose_name='Mensaje de saludo')),
                ('menu_enabled', models.BooleanField(default=True, help_text='Si está activo, el primer mensaje incluye el menú de opciones.', verbose_name='Menú interactivo activo')),
                ('webhook_secret', models.CharField(blank=True, help_text='Clave para autenticar las peticiones de n8n', max_length=200, verbose_name='API Key para webhooks')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuraciones de negocios',
            },
        ),
    ]
