# Generated by Django 5.1 on 2026-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict, help_text='Datos extra: horarios, redes sociales, etc.', verbose_name='Información de contacto extra'),
        ),
        migrations.AlterField(
            model_name='businessconfig',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', help_text='Modelo de OpenAI a usar (gpt-4o-mini, gpt-4o, etc.)', max_length=100, verbose_name='Modelo de IA'),
        ),
    ]
