# Generated by Django 5.2.8 on 2026-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='ai_max_messages',
            field=models.IntegerField(default=0, help_text='Derivar a humano tras N mensajes de IA sin resolver. 0 = sin límite.', verbose_name='Límite mensajes IA'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='auto_assign_enabled',
            field=models.BooleanField(default=False, help_text='Asignar automáticamente conversaciones a agentes por especialización.', verbose_name='Auto-asignación'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='auto_close_hours',
            field=models.IntegerField(default=0, help_text='Cerrar conversaciones inactivas después de X horas. 0 = desactivado.', verbose_name='Auto-cierre (horas)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='Clasificaciones que este agente atiende (ej: ventas, reclamos). Vacío = atiende todo.', verbose_name='Especializaciones'),
        ),
    ]
