# Generated by Django 5.1 on 2026-03-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businessconfig_ai_max_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='agent_visibility_mode',
            field=models.CharField(choices=[('all', 'Ver no asignadas + propias'), ('assigned_only', 'Solo asignadas')], default='all', help_text='all = agentes ven conversaciones no asignadas + las suyas. assigned_only = solo las asignadas.', max_length=20, verbose_name='Visibilidad de agentes'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='supervisor_only_mode',
            field=models.BooleanField(default=False, help_text='Si está activo, no se auto-asigna nada y todos ven todas las conversaciones.', verbose_name='Modo solo supervisores'),
        ),
    ]
