# Generated by Django 5.1 on 2026-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessconfig_agent_visibility_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, help_text='Phone Number ID de Meta (se encuentra en el dashboard de WhatsApp Business)', max_length=100, verbose_name='WhatsApp Phone Number ID'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='whatsapp_token',
            field=models.CharField(blank=True, help_text='Token de acceso permanente de la WhatsApp Cloud API', max_length=500, verbose_name='WhatsApp Access Token'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='whatsapp_verify_token',
            field=models.CharField(blank=True, help_text='Token de verificación elegido por vos para validar el webhook de Meta', max_length=200, verbose_name='WhatsApp Verify Token'),
        ),
        migrations.AlterField(
            model_name='businessconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Clave para autenticar las peticiones entrantes al webhook', max_length=200, verbose_name='API Key para webhooks'),
        ),
    ]
