# Generated by Django 5.1 on 2026-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_businessconfig_whatsapp_phone_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con horarios. Ejemplo: {"lun-vie": "9:00-18:00", "sab": "9:00-13:00"}', verbose_name='Horarios del negocio'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='escalation_message',
            field=models.TextField(blank=True, default='👤 Te voy a comunicar con un agente para ayudarte mejor. En breve te atiende una persona. ¡Gracias por tu paciencia!', help_text='Se envía cuando la conversación se deriva a un humano.', verbose_name='Mensaje de derivación a humano'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='menu_force_selection',
            field=models.BooleanField(default=True, help_text='Si está activo, el cliente debe elegir una opción del menú con un número. Si no, puede escribir texto libre y la IA responde.', verbose_name='Obligar selección del menú'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='menu_reactivation_message',
            field=models.CharField(blank=True, default='📋 _Escribí *1* para volver al menú._', help_text='Se agrega al final de cada respuesta de la IA para que el cliente pueda volver al menú.', max_length=300, verbose_name='Mensaje de reactivación del menú'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='out_of_hours_message',
            field=models.TextField(blank=True, help_text='Se envía automáticamente fuera de horario. Vacío = no se envía.', verbose_name='Mensaje fuera de horario'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='welcome_back_message',
            field=models.TextField(blank=True, help_text='Mensaje para clientes que ya escribieron antes. Vacío = se usa el saludo normal.', verbose_name='Mensaje de bienvenida recurrente'),
        ),
    ]
