# Generated by Django 5.1 on 2026-03-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='ai_feedback_enabled',
            field=models.BooleanField(default=True, help_text='Permitir a los administradores calificar las respuestas de la IA.', verbose_name='Feedback IA activado'),
        ),
    ]
