# Generated by Django 5.1 on 2026-03-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_businessconfig_ai_feedback_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='business_hours_enabled',
            field=models.BooleanField(default=True, help_text='Si está activo, la plataforma evalúa los horarios para decidir si responder dentro o fuera de horario.', verbose_name='Horarios habilitados'),
        ),
    ]
