# Generated by Django 5.2.12 on 2026-04-19 00:39

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businessconfig_business_hours_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='whatsapp_app_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='App Secret de la app de Meta. Si está cargado, el webhook valida X-Hub-Signature-256 antes de procesar.', max_length=500, verbose_name='WhatsApp App Secret'),
        ),
        migrations.AlterField(
            model_name='businessconfig',
            name='whatsapp_token',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Token de acceso permanente de la WhatsApp Cloud API', max_length=2000, verbose_name='WhatsApp Access Token'),
        ),
    ]
