# Generated by Django 5.2.12 on 2026-04-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_channels_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='ai_globally_disabled',
            field=models.BooleanField(default=False, help_text='Si está activo, la IA no responde automáticamente. Solo funciona el menú interactivo y la atención humana.', verbose_name='Desactivar IA globalmente'),
        ),
    ]
