# Generated by Django 5.2.12 on 2026-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ai_globally_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='ai_auto_summary_interval',
            field=models.IntegerField(default=0, help_text='La IA regenera el resumen automáticamente cada N mensajes recibidos. 0 = desactivado.', verbose_name='Auto-resumen cada N mensajes'),
        ),
    ]
