# Generated by Django 5.2.12 on 2026-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_summary_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='feature_appointments',
            field=models.BooleanField(default=False, help_text='Habilita el sistema de citas online (calendario, reservas por IA). Solo activar si el cliente contrató este módulo.', verbose_name='Módulo de citas habilitado'),
        ),
    ]
