# Generated by Django 5.2.12 on 2026-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_feature_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='ai_mode',
            field=models.CharField(choices=[('full', 'IA completa (responde todo)'), ('menu_handoff', 'Menú + turnos (deriva a agente para chat libre)'), ('menu_only', 'Solo menú (sin IA, sin derivación automática)')], default='full', help_text='Controla cómo usa la IA el bot.', max_length=20, verbose_name='Modo de IA'),
        ),
        migrations.AlterField(
            model_name='businessconfig',
            name='ai_globally_disabled',
            field=models.BooleanField(default=False, help_text='Reemplazado por Modo de IA. Si está activo se trata como "Solo menú".', verbose_name='Desactivar IA globalmente (legacy)'),
        ),
    ]
