# Generated by Django 5.1 on 2026-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ai_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='ai_auto_reactivate_unit',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas')], default='minutes', max_length=10, verbose_name='Unidad de reactivación'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='ai_auto_reactivate_value',
            field=models.IntegerField(default=0, help_text='Tiempo de inactividad tras el cual se reactiva la IA automáticamente. 0 = desactivado.', verbose_name='Reactivación automática de IA'),
        ),
    ]
