# Generated by Django 5.2.12 on 2026-04-20 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0010_channels_migration'),
        ('core', '0012_ai_globally_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Sistema de citas activo')),
                ('slot_name', models.CharField(default='Cita', help_text='Ej: Cita, Turno, Consulta, Reunión', max_length=50, verbose_name='Nombre del turno')),
                ('appointment_duration', models.IntegerField(default=60, help_text='Duración de cada cita en minutos.', verbose_name='Duración por cita (min)')),
                ('buffer_time', models.IntegerField(default=0, help_text='Tiempo de preparación entre citas consecutivas.', verbose_name='Tiempo entre citas (min)')),
                ('max_per_day', models.IntegerField(default=0, help_text='0 = sin límite.', verbose_name='Máx. citas por día')),
                ('max_concurrent', models.IntegerField(default=1, help_text='Cuántas citas pueden coexistir en el mismo horario.', verbose_name='Citas simultáneas por horario')),
                ('advance_booking_days', models.IntegerField(default=30, help_text='Con cuántos días de anticipación se puede reservar.', verbose_name='Días de anticipación máxima')),
                ('min_advance_hours', models.IntegerField(default=2, help_text='Mínimo de horas antes del turno para poder reservarlo.', verbose_name='Horas mínimas de anticipación')),
                ('confirmation_message', models.TextField(blank=True, default='✅ ¡{slot_name} confirmada!\n📅 Fecha: {date}\n🕐 Hora: {time}\n\nSi necesitás cancelar o reprogramar, escribinos con anticipación.', verbose_name='Mensaje de confirmación')),
                ('cancellation_message', models.TextField(blank=True, default='❌ Tu {slot_name} del {date} a las {time} fue cancelada.\n¿Querés reagendar? Escribinos cuando quieras.', verbose_name='Mensaje de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_config', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Configuración de citas',
                'verbose_name_plural': 'Configuraciones de citas',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No se presentó')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by_ai', models.BooleanField(default=False, verbose_name='Creada por IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='conversations.conversation')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.appointmentconfig', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='Día completo')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='appointments.appointmentconfig', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Período bloqueado',
                'verbose_name_plural': 'Períodos bloqueados',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='appointments.appointmentconfig', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Disponibilidad semanal',
                'verbose_name_plural': 'Disponibilidades semanales',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
