# Generated by Django 5.1 on 2026-03-09 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='Identificador en la plataforma (ej: número de WhatsApp)', max_length=200, verbose_name='ID externo')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('web', 'Web'), ('telegram', 'Telegram'), ('otro', 'Otro')], default='whatsapp', max_length=20, verbose_name='Plataforma')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Primer contacto')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'external_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=20, verbose_name='Estado')),
                ('classification', models.CharField(blank=True, help_text='Etiqueta asignada por la IA. El recepcionista puede cambiarla.', max_length=50, verbose_name='Clasificación')),
                ('classification_confidence', models.FloatField(default=0.0, help_text='Confianza de la IA en la clasificación (0.0 a 1.0)', verbose_name='Confianza')),
                ('summary', models.TextField(blank=True, help_text='Resumen automático de lo que quiere el contacto para el recepcionista.', verbose_name='Resumen IA')),
                ('menu_state', models.CharField(choices=[('initial', 'Mensaje inicial'), ('main_menu', 'Menú principal'), ('submenu', 'Sub-menú'), ('ai_chat', 'Chat con IA'), ('human_chat', 'Chat con humano')], default='initial', max_length=20, verbose_name='Estado del menú')),
                ('menu_selections', models.JSONField(blank=True, default=list, help_text='Historial de selecciones del menú del usuario.', verbose_name='Selecciones del menú')),
                ('current_menu_category_id', models.IntegerField(blank=True, help_text='ID de la categoría del menú en la que está el usuario.', null=True, verbose_name='Categoría actual del menú')),
                ('is_ai_active', models.BooleanField(default=True, help_text='Si está activo, la IA responde automáticamente. Si no, solo responde el humano.', verbose_name='IA activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Último mensaje')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.business', verbose_name='Negocio')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'IA'), ('agent', 'Recepcionista'), ('system', 'Sistema')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos extra: tipo de media, archivos adjuntos, etc.', verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
    ]
