# Generated by Django 5.1 on 2026-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('en_seguimiento', 'En seguimiento'), ('esperando_cliente', 'Esperando cliente'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('archivada', 'Archivada')], default='activa', max_length=20, verbose_name='Estado'),
        ),
    ]
