# Generated by Django 5.2.8 on 2026-03-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='current_menu_category_id',
            field=models.CharField(blank=True, help_text='ID de la categoría del menú en la que está el usuario.', max_length=50, null=True, verbose_name='Categoría actual del menú'),
        ),
    ]
