# Generated by Django 5.2.8 on 2026-03-10 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_conversation_current_menu_category_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Agente asignado'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='human_needed_at',
            field=models.DateTimeField(blank=True, help_text='Útil para medir el SLA (tiempo de espera) desde que el cliente esperó al agente.', null=True, verbose_name='Humano solicitado el'),
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='conversations.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Nota de Contacto',
                'verbose_name_plural': 'Notas de Contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
