# Generated by Django 5.1 on 2026-03-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_menu_subcategory_id',
            field=models.CharField(blank=True, help_text='ID de la subcategoría del menú (para 3er nivel).', max_length=50, null=True, verbose_name='Subcategoría actual del menú'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='menu_state',
            field=models.CharField(choices=[('initial', 'Mensaje inicial'), ('main_menu', 'Menú principal'), ('submenu', 'Sub-menú'), ('sub_submenu', 'Sub-sub-menú'), ('ai_chat', 'Chat con IA'), ('human_chat', 'Chat con humano')], default='initial', max_length=20, verbose_name='Estado del menú'),
        ),
    ]
