# Generated by Django 5.1 on 2026-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_conversation_current_menu_subcategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='menu_state',
            field=models.CharField(choices=[('initial', 'Mensaje inicial'), ('main_menu', 'Menú principal'), ('submenu', 'Sub-menú'), ('sub_submenu', 'Sub-sub-menú'), ('menu_response', 'Respuesta de menú'), ('ai_chat', 'Chat con IA'), ('human_chat', 'Chat con humano')], default='initial', max_length=20, verbose_name='Estado del menú'),
        ),
    ]
