# Generated by Django 5.1 on 2026-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_alter_conversation_menu_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='panel_unread_count',
            field=models.IntegerField(default=0, help_text='Cantidad de mensajes del cliente no leídos por el panel.', verbose_name='Mensajes no leídos'),
        ),
    ]
