# Generated by Django 5.1 on 2026-03-25 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_conversation_panel_unread_count'),
        ('core', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='panel_unread_count',
            field=models.IntegerField(default=0, help_text='Cantidad de mensajes nuevos del cliente desde que un agente abrió el chat por última vez.', verbose_name='Mensajes no leídos'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de etiqueta')),
                ('color', models.CharField(default='#3b82f6', max_length=30, verbose_name='Color (Hex, css)')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='conversations.tag', verbose_name='Etiquetas'),
        ),
    ]
