# Generated by Django 5.1 on 2026-03-25 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_alter_conversation_panel_unread_count_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo estimado en dólares.', max_digits=10, verbose_name='Costo USD'),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Tokens consumidos por la IA en este mensaje.', verbose_name='Tokens'),
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '👍 Positivo'), (-1, '👎 Negativo')], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario opcional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversations.message', verbose_name='Mensaje IA')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Feedback de IA',
                'verbose_name_plural': 'Feedbacks de IA',
            },
        ),
    ]
