# Generated by Django 5.2.12 on 2026-04-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_message_ai_cost_message_tokens_used_aifeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_messages_in_session',
            field=models.IntegerField(default=0, help_text='Cantidad de mensajes generados por IA en la sesión actual. Se resetea al reactivar la IA.', verbose_name='Mensajes IA en sesión'),
        ),
    ]
