# Generated by Django 5.2.12 on 2026-04-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_menu_state_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='menu_state',
            field=models.CharField(choices=[('initial', 'Mensaje inicial'), ('main_menu', 'Menú principal'), ('submenu', 'Sub-menú'), ('sub_submenu', 'Sub-sub-menú'), ('menu_response', 'Respuesta de menú'), ('ai_chat', 'Chat con IA'), ('human_chat', 'Chat con humano'), ('appointment_slot_selection', 'Selección de turno'), ('appointment_cancel_selection', 'Cancelación de turno')], default='initial', max_length=50, verbose_name='Estado del menú'),
        ),
    ]
